# Generated by Django 6.0.7 on 2026-08-20 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailycheckin',
            old_name='mote',
            new_name='note',
        ),
    ]
