# Generated by Django 6.0.7 on 2026-08-21 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0002_rename_mote_dailycheckin_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='mood',
            field=models.CharField(choices=[('calm', 'Calm'), ('okay', 'Okay'), ('stressed', 'Stressed'), ('overwhelmed', 'Overwhelmed'), ('motivated', 'Motivated'), ('tired', 'Tired')], max_length=20),
        ),
    ]
