# Generated by Django 6.0.7 on 2026-08-24 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0003_alter_dailycheckin_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('recovery', 'Recovery'), ('low_energy', 'Low Energy'), ('steady', 'Steady'), ('balanced', 'Balanced'), ('progress', 'Progress')], max_length=20)),
                ('routine_type', models.CharField(choices=[('morning', 'Morning'), ('study', 'Study'), ('cleaning', 'Cleaning'), ('cooking', 'Cooking'), ('evening', 'Evening')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('focus', 'Focus'), ('starting', 'Getting Started'), ('organisation', 'Organisation'), ('recovery', 'Recovery'), ('study', 'Study'), ('routine', 'Routine')], max_length=20)),
                ('energy_level', models.CharField(choices=[('any', 'Any'), ('low', 'Low'), ('medium', 'Medium'), ('good', 'Good')], default='any', max_length=20)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('resource_url', models.URLField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='wellbeing.routine')),
                ('strategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wellbeing.strategy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
