# Generated by Django 6.0.7 on 2026-09-06 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0004_routine_strategy_routinestep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strategy',
            options={'verbose_name_plural': 'Strategies'},
        ),
        migrations.AddField(
            model_name='routine',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL),
        ),
    ]
