# Generated by Django 6.0.7 on 2026-09-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0005_alter_strategy_options_routine_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='short_tip',
            field=models.CharField(blank=True, help_text='A short, one-line version of this strategy, used for the pop-up tip. Leave blank to fall back to a trimmed description.', max_length=150),
        ),
    ]
