# Generated by Django 6.0.7 on 2026-09-06 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0006_strategy_short_tip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DopamineMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('starters', 'Starters (10-15 minutes)'), ('mains', 'Mains (about an hour)'), ('sides', 'Sides (alongside something else)'), ('desserts', 'Desserts (good in moderation)'), ('specials', 'Specials (rare treats)'), ('salads', 'Salads (good for you, harder to start)')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnergyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField(help_text='Positive number for a deposit, negative for a withdrawal.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Energy entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
