# Generated by Django 6.0.7 on 2026-09-06 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0007_dopaminemenuitem_energyentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DopamineMenuItem',
        ),
    ]
