# Generated by Django 6.0.7 on 2026-09-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellbeing', '0008_delete_dopaminemenuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DopamineMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('starters', 'Starters (10-15 minutes)'), ('mains', 'Mains (about an hour)'), ('sides', 'Sides (alongside something else)'), ('desserts', 'Desserts (good in moderation)'), ('specials', 'Specials (rare treats)'), ('salads', 'Salads (good for you, harder to start)')], max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EnergyEntry',
        ),
    ]
