# Generated by Django 6.0.7 on 2026-09-07 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
